env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
rules:
  no-console:
    - off
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - off
  no-control-regex:
    - off
