language: node_js
node_js:
   - "node"
install:
  - npm run app-install
script:
  - npm run pretest:client
  - npm run pretest:server  
cache:
  directories:
    - node_modules   
    - client/node_modules
    - server/node_modules